version: '3.8'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/my-fullstack-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
  backend:
    image: ${DOCKERHUB_USERNAME}/my-fullstack-backend:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=${NODE_ENV}
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"
volumes:
  db_data:
