version: '3.8'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/my-fullstack-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
  backend:
    image: ${DOCKERHUB_USERNAME}/my-fullstack-backend:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=vo_huuthang
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - NODE_ENV=${NODE_ENV}
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  db_data:
