name: developer

on:
  push:
    branches:
      - main
      - feat/fullstack-docker

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-frontend:latest ./frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-frontend:latest

      - name: Pull backend image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-backend:latest

      - name: Pull frontend image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-fullstack-frontend:latest

      - name: Docker Compose Down
        run: docker-compose down || true

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Clean up Docker images (optional)
        run: docker image prune -f